import { v4 as uuidv4 } from 'uuid';
import { VEHICLES_DATA } from '../vehicles/vehicles-data.js';

export enum OrderStatus {
  pending = 'Oczekujące',
  inProgress = 'W trakcie',
  completed = 'Ukończone',
}

export interface OrderInterface {
  id: string;
  pickupLocation: string;
  deliveryLocation: string;
  cargoDescription: string;
  pickupTime: string;
  deliveryTime: string;
  vehicleId: string | null;
  driverId: string | null;
  status: OrderStatus;
}

export const ORDERS_DATA: OrderInterface[] = [
  {
    id: uuidv4(),
    pickupLocation: 'Warszawa, Polska',
    deliveryLocation: 'Kraków, Polska',
    cargoDescription: 'Paczka o wymiarach 30x20x15 cm',
    pickupTime: '2023-11-01T10:00:00Z',
    deliveryTime: '2023-11-01T14:00:00Z',
    vehicleId: VEHICLES_DATA[0].id,
    driverId: VEHICLES_DATA[0].driverId,
    status: OrderStatus.pending,
  },
  {
    id: uuidv4(),
    pickupLocation: 'Gdańsk, Polska',
    deliveryLocation: 'Szczecin, Polska',
    cargoDescription: 'Paleta z towarem',
    pickupTime: '2023-11-02T08:30:00Z',
    deliveryTime: '2023-11-02T16:30:00Z',
    vehicleId: VEHICLES_DATA[1].id,
    driverId: VEHICLES_DATA[1].driverId,
    status: OrderStatus.inProgress,
  },
  {
    id: uuidv4(),
    pickupLocation: 'Paryż, Francja',
    deliveryLocation: 'Berlin, Niemcy',
    cargoDescription: 'Skrzynka z dokumentami',
    pickupTime: '2023-11-03T09:15:00Z',
    deliveryTime: '2023-11-03T15:45:00Z',
    vehicleId: VEHICLES_DATA[2].id,
    driverId: VEHICLES_DATA[2].driverId,
    status: OrderStatus.completed,
  },
  {
    id: uuidv4(),
    pickupLocation: 'Poznań, Polska',
    deliveryLocation: 'Łódź, Polska',
    cargoDescription: 'Paleta z produktami spożywczymi',
    pickupTime: '2023-11-04T11:30:00Z',
    deliveryTime: '2023-11-04T15:45:00Z',
    vehicleId: VEHICLES_DATA[2].id,
    driverId: VEHICLES_DATA[2].driverId,
    status: OrderStatus.pending,
  },
  {
    id: uuidv4(),
    pickupLocation: 'Wrocław, Polska',
    deliveryLocation: 'Katowice, Polska',
    cargoDescription: 'Paczki kurierskie',
    pickupTime: '2023-11-05T09:00:00Z',
    deliveryTime: '2023-11-05T12:30:00Z',
    vehicleId: VEHICLES_DATA[3].id,
    driverId: VEHICLES_DATA[3].driverId,
    status: OrderStatus.inProgress,
  },
  {
    id: uuidv4(),
    pickupLocation: 'Budapeszt, Węgry',
    deliveryLocation: 'Praga, Czechy',
    cargoDescription: 'Maszyny przemysłowe',
    pickupTime: '2023-11-06T14:00:00Z',
    deliveryTime: '2023-11-06T20:30:00Z',
    vehicleId: VEHICLES_DATA[6].id,
    driverId: VEHICLES_DATA[6].driverId,
    status: OrderStatus.completed,
  },
  {
    id: uuidv4(),
    pickupLocation: 'Madryt, Hiszpania',
    deliveryLocation: 'Lizbona, Portugalia',
    cargoDescription: 'Materiały budowlane',
    pickupTime: '2023-11-07T10:45:00Z',
    deliveryTime: '2023-11-07T18:15:00Z',
    vehicleId: VEHICLES_DATA[7].id,
    driverId: VEHICLES_DATA[7].driverId,
    status: OrderStatus.completed,
  },
  {
    id: uuidv4(),
    pickupLocation: 'Londyn, Wielka Brytania',
    deliveryLocation: 'Dublin, Irlandia',
    cargoDescription: 'Elektronika',
    pickupTime: '2023-11-08T13:30:00Z',
    deliveryTime: '2023-11-08T17:00:00Z',
    vehicleId: VEHICLES_DATA[7].id,
    driverId: VEHICLES_DATA[7].driverId,
    status: OrderStatus.pending,
  },
  {
    id: uuidv4(),
    pickupLocation: 'Berlin, Niemcy',
    deliveryLocation: 'Wiedeń, Austria',
    cargoDescription: 'Ubrania i akcesoria modowe',
    pickupTime: '2023-11-09T09:30:00Z',
    deliveryTime: '2023-11-09T14:00:00Z',
    vehicleId: VEHICLES_DATA[9].id,
    driverId: VEHICLES_DATA[9].driverId,
    status: OrderStatus.inProgress,
  },
  {
    id: uuidv4(),
    pickupLocation: 'Rzym, Włochy',
    deliveryLocation: 'Ateny, Grecja',
    cargoDescription: 'Artykuły spożywcze',
    pickupTime: '2023-11-10T12:00:00Z',
    deliveryTime: '2023-11-10T18:30:00Z',
    vehicleId: VEHICLES_DATA[0].id,
    driverId: VEHICLES_DATA[0].driverId,
    status: OrderStatus.inProgress,
  },
  {
    id: uuidv4(),
    pickupLocation: 'Praga, Czechy',
    deliveryLocation: 'Budapeszt, Węgry',
    cargoDescription: 'Elektronika konsumencka',
    pickupTime: '2023-11-11T15:15:00Z',
    deliveryTime: '2023-11-11T20:45:00Z',
    vehicleId: VEHICLES_DATA[1].id,
    driverId: VEHICLES_DATA[1].driverId,
    status: OrderStatus.pending,
  },
  {
    id: uuidv4(),
    pickupLocation: 'Barcelona, Hiszpania',
    deliveryLocation: 'Lyon, Francja',
    cargoDescription: 'Produkty chemiczne',
    pickupTime: '2023-11-12T10:45:00Z',
    deliveryTime: '2023-11-12T16:30:00Z',
    vehicleId: VEHICLES_DATA[1].id,
    driverId: VEHICLES_DATA[1].driverId,
    status: OrderStatus.completed,
  },
  {
    id: uuidv4(),
    pickupLocation: 'Amsterdam, Holandia',
    deliveryLocation: 'Bruksela, Belgia',
    cargoDescription: 'Książki i magazyny',
    pickupTime: '2023-11-13T11:30:00Z',
    deliveryTime: '2023-11-13T15:45:00Z',
    vehicleId: VEHICLES_DATA[3].id,
    driverId: VEHICLES_DATA[3].driverId,
    status: OrderStatus.completed,
  },
  {
    id: uuidv4(),
    pickupLocation: 'Hamburg, Niemcy',
    deliveryLocation: 'Sztokholm, Szwecja',
    cargoDescription: 'Materiały budowlane',
    pickupTime: '2023-11-14T08:00:00Z',
    deliveryTime: '2023-11-14T14:30:00Z',
    vehicleId: VEHICLES_DATA[6].id,
    driverId: VEHICLES_DATA[6].driverId,
    status: OrderStatus.inProgress,
  },
  {
    id: uuidv4(),
    pickupLocation: 'Oslo, Norwegia',
    deliveryLocation: 'Kopenhaga, Dania',
    cargoDescription: 'Urządzenia elektryczne',
    pickupTime: '2023-11-15T09:45:00Z',
    deliveryTime: '2023-11-15T16:15:00Z',
    vehicleId: VEHICLES_DATA[2].id,
    driverId: VEHICLES_DATA[2].driverId,
    status: OrderStatus.inProgress,
  },
  {
    id: uuidv4(),
    pickupLocation: 'Zurych, Szwajcaria',
    deliveryLocation: 'Wiedeń, Austria',
    cargoDescription: 'Meble',
    pickupTime: '2023-11-16T13:30:00Z',
    deliveryTime: '2023-11-16T18:45:00Z',
    vehicleId: VEHICLES_DATA[6].id,
    driverId: VEHICLES_DATA[6].driverId,
    status: OrderStatus.pending,
  },
  {
    id: uuidv4(),
    pickupLocation: 'Brygge, Belgia',
    deliveryLocation: 'Luksemburg, Luksemburg',
    cargoDescription: 'Produkty spożywcze',
    pickupTime: '2023-11-17T10:30:00Z',
    deliveryTime: '2023-11-17T14:45:00Z',
    vehicleId: VEHICLES_DATA[0].id,
    driverId: VEHICLES_DATA[0].driverId,
    status: OrderStatus.completed,
  },
  {
    id: uuidv4(),
    pickupLocation: 'Rzym, Włochy',
    deliveryLocation: 'Madryt, Hiszpania',
    cargoDescription: 'Samochodowe części zamiennikowe',
    pickupTime: '2023-11-18T11:15:00Z',
    deliveryTime: '2023-11-18T18:00:00Z',
    vehicleId: VEHICLES_DATA[0].id,
    driverId: VEHICLES_DATA[0].driverId,
    status: OrderStatus.completed,
  },
  {
    id: uuidv4(),
    pickupLocation: 'Praga, Czechy',
    deliveryLocation: 'Budapeszt, Węgry',
    cargoDescription: 'Elektronika konsumencka',
    pickupTime: '2023-11-19T09:30:00Z',
    deliveryTime: '2023-11-19T14:00:00Z',
    vehicleId: VEHICLES_DATA[6].id,
    driverId: VEHICLES_DATA[6].driverId,
    status: OrderStatus.inProgress,
  },
  {
    id: uuidv4(),
    pickupLocation: 'Wiedeń, Austria',
    deliveryLocation: 'Zagrzeb, Chorwacja',
    cargoDescription: 'Meble ogrodowe',
    pickupTime: '2023-11-20T12:00:00Z',
    deliveryTime: '2023-11-20T18:30:00Z',
    vehicleId: VEHICLES_DATA[9].id,
    driverId: VEHICLES_DATA[9].driverId,
    status: OrderStatus.inProgress,
  },
  {
    id: uuidv4(),
    pickupLocation: 'Amsterdam, Holandia',
    deliveryLocation: 'Bruksela, Belgia',
    cargoDescription: 'Artykuły spożywcze',
    pickupTime: '2023-11-21T15:15:00Z',
    deliveryTime: '2023-11-21T20:45:00Z',
    vehicleId: VEHICLES_DATA[7].id,
    driverId: VEHICLES_DATA[7].driverId,
    status: OrderStatus.pending,
  },
  {
    id: uuidv4(),
    pickupLocation: 'Paryż, Francja',
    deliveryLocation: 'Londyn, Wielka Brytania',
    cargoDescription: 'Książki i magazyny',
    pickupTime: '2023-11-22T10:45:00Z',
    deliveryTime: '2023-11-22T16:30:00Z',
    vehicleId: VEHICLES_DATA[3].id,
    driverId: VEHICLES_DATA[3].driverId,
    status: OrderStatus.completed,
  },
  {
    id: uuidv4(),
    pickupLocation: 'Berlin, Niemcy',
    deliveryLocation: 'Kraków, Polska',
    cargoDescription: 'Samochodowe części zamiennikowe',
    pickupTime: '2023-11-23T11:30:00Z',
    deliveryTime: '2023-11-23T15:45:00Z',
    vehicleId: VEHICLES_DATA[2].id,
    driverId: VEHICLES_DATA[2].driverId,
    status: OrderStatus.completed,
  },
];
